<!DOCTYPE html>
<html lang="en">

<title>PS70: Intro to Digital Fabrication </title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="../style.css" rel="stylesheet">


<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <div style="align-items: left; justify-content:left;" class="container-fluid">
    <h3 class="nav-title"> PS70: Intro to Digital Fabrication</h3>
    <div class="navbar-nav">
      <h4></h4>
      <h4><a class="nav-link" href="../index.html">Home</a></h4>
      <h4><a class="nav-link" href="../about.html">About Me & My Final Project</a></h4>
    </div>
  </div>
</nav>

<body>


<xmp style="display:none;">
<br> 

## 3: Kinetic Scultpure

Our assignment was to build a kinetic sculpture using circuitry. I came up with a boat that would rock back and forth using wire and a motor, so I drew out my design first.

<img src="boat design.jpg" width="330" height="420">

After designing it I redrew it in Fusion360. 

## For the boat shape: 
I used a diameter of 152.40 mm and then split it in half to make two semi-circles. I created a hole with a diameter of 1.00 mm centered 38.1 mm from the bottom of the shape and 38.1 mm from the side of the shape. 
For the underside of the boat shape I halfed the circumferense of the circles to make the length of the rectangle shape and the width would be 76.20 mm. For the top of the boat shape I made another rectangle with the measurements of 76.20 mm by 152.40 mm with a hole with a diameter of 1.00 mm centered in the center of the shape.

## For the sail shape:
I made a triangle with I hieght of 76.2 mm and a width of 152.4 mm. I placed a line down the midpoint to create two symetrical triangle. I plan on putting a wire in between the two triangles to make the finished sail.

## For the box shape:
For the base i used the measurement of 279.4 mm by 203.2 mm. I made the sides with 2 rectangles measured 203.20 mm x 101.60 mm and 2 rectangles measuring 279.40 mm x 101.60 mm.
<img src="boat fusion.PNG" width="920" height="550">

## Making a built in place for the motor and curcuit:
For the supports I used the diameter of the round end of the motor in Fusion360 and then offset it outwards by 5.00 mm. I found the midpoint of the outer most line and place a rectangle with the measurement of ___ into it. For the other side I used the length and width of the rectangular end of the motor (18.76 mm x 22.35 mm) and offsetted that number by 5.00 mm. I added the same rectangle to the midpoint of the __ mm side and trimmed the unneeded lines. 
<img src="motor holder.PNG" width="920" height="550">

## Added legs to the bottom of the box:
I wanted a place to put the wires and boards neatly so I made a hollow leg where the wires could sit in underneath the sculpture. I used simple rectangles to make them. Using multiple rectangles that measured 45 mm x 79 mm and 45 mm x 37mm.
<img src="boat box legs.PNG" width="920" height="550">

# Finished Product
<video src="finished boat.mp4" class="object-fit-fill" autoplay width="820" height="450"></video>

</xmp>
</body>

<script src="../strapdown.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" ></script>

</html>